version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # db is the database folder. Select specifically the ARM-system-based dockerfile.
  db:
    platform: linux/amd64
    build:
      context: "./db"
      dockerfile: "Dockerfile.arm"
    command: --default-authentication-plugin=mysql_native_password
    restart: always

    # Open and make ports listen for faster connection to the database.
    ports:
      - "33060:3306"