version: '3'
services:
  # Application Dockerfile is in same folder which is .
  app:
    build: .

  # db is database folder. Selects dockerfile in the directory by default
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always

  # Open and make ports listen for faster connection to the database.
    ports:
      - "33060:3306"
